name: Pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - master
      - "release-**"

env:
  NODE_OPTIONS: "--max-old-space-size=8192"
jobs:
  lint-check:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
      - run: make lint-check
  format-check:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
      - run: make format-check
  type-check:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
      - run: make type-check
  security-scan:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
      - run: make security-scan
  test:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
      - run: make test
  build:
    if: ${{ ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODEJS_VERSION }}
      - run: make build
